alter table public.profiles drop constraint if exists profiles_id_fkey;

alter table public.profiles disable row level security;
alter table public.profile_heart_rate_zones disable row level security;
alter table public.profile_weekly_schedule_entries disable row level security;
alter table public.coach_memory disable row level security;
alter table public.user_preferences disable row level security;
alter table public.import_batches disable row level security;
alter table public.health_daily disable row level security;
alter table public.sleep_timeline_points disable row level security;
alter table public.heart_rate_intraday_points disable row level security;
alter table public.steps_hourly_points disable row level security;
alter table public.workouts disable row level security;
alter table public.workout_exercises disable row level security;
alter table public.personal_records disable row level security;
alter table public.personal_record_entries disable row level security;
alter table public.chat_folders disable row level security;
alter table public.chat_sessions disable row level security;
alter table public.chat_messages disable row level security;

drop policy if exists "profiles own rows" on public.profiles;
drop policy if exists "profile_heart_rate_zones own rows" on public.profile_heart_rate_zones;
drop policy if exists "profile_weekly_schedule_entries own rows" on public.profile_weekly_schedule_entries;
drop policy if exists "coach_memory own rows" on public.coach_memory;
drop policy if exists "user_preferences own rows" on public.user_preferences;
drop policy if exists "import_batches own rows" on public.import_batches;
drop policy if exists "health_daily own rows" on public.health_daily;
drop policy if exists "sleep_timeline_points own rows" on public.sleep_timeline_points;
drop policy if exists "heart_rate_intraday_points own rows" on public.heart_rate_intraday_points;
drop policy if exists "steps_hourly_points own rows" on public.steps_hourly_points;
drop policy if exists "workouts own rows" on public.workouts;
drop policy if exists "workout_exercises own rows" on public.workout_exercises;
drop policy if exists "personal_records own rows" on public.personal_records;
drop policy if exists "personal_record_entries own rows" on public.personal_record_entries;
drop policy if exists "chat_folders own rows" on public.chat_folders;
drop policy if exists "chat_sessions own rows" on public.chat_sessions;
drop policy if exists "chat_messages own rows" on public.chat_messages;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.profiles to anon, authenticated;
grant select, insert, update, delete on table public.profile_heart_rate_zones to anon, authenticated;
grant select, insert, update, delete on table public.profile_weekly_schedule_entries to anon, authenticated;
grant select, insert, update, delete on table public.coach_memory to anon, authenticated;
grant select, insert, update, delete on table public.user_preferences to anon, authenticated;
grant select, insert, update, delete on table public.import_batches to anon, authenticated;
grant select, insert, update, delete on table public.health_daily to anon, authenticated;
grant select, insert, update, delete on table public.sleep_timeline_points to anon, authenticated;
grant select, insert, update, delete on table public.heart_rate_intraday_points to anon, authenticated;
grant select, insert, update, delete on table public.steps_hourly_points to anon, authenticated;
grant select, insert, update, delete on table public.workouts to anon, authenticated;
grant select, insert, update, delete on table public.workout_exercises to anon, authenticated;
grant select, insert, update, delete on table public.personal_records to anon, authenticated;
grant select, insert, update, delete on table public.personal_record_entries to anon, authenticated;
grant select, insert, update, delete on table public.chat_folders to anon, authenticated;
grant select, insert, update, delete on table public.chat_sessions to anon, authenticated;
grant select, insert, update, delete on table public.chat_messages to anon, authenticated;
